server:
  port: 8080

spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      db1:
        url: jdbc:mysql://localhost:3306/jackal-db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        url: jdbc:mysql://localhost:3306/spigot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml